const mongoose=require("mongoose");
const ProductSchema=new mongoose.Schema(
    {
        product_id:{
            type:Number,
            required:true,
            unique:true
        },
        name:{
            type:String,
            required:true,
        },
        description:{
            type:String,
            required:true,
        },
        productImg:{
            type:String,
            required:true,
        },
        new_price:{
            type:Number,
            require:true,
        },
        old_price:{
            type:Number,
            require:true,
        },
        product_qty:{
            type:Number,
            require:true,
        },
        category:{
            type:String,
            require:true,
        },
        sub_category:{
            type:String,
            require:true,
        },
        rating:{
            type:Number,
            require:true,
        },
        colors:{
            type:Array,
            require:true,
        },
    });
const ProductCollection=mongoose.model("products",ProductSchema);
module.exports=ProductCollection;
